export const currencies: Currency[] = [
  { code: 'USD', name: 'Dólar estadounidense' },
  { code: 'EUR', name: 'Euro' },
  { code: 'JPY', name: 'Yen japonés' },
  { code: 'GBP', name: 'Libra esterlina' },
  { code: 'AUD', name: 'Dólar australiano' },
  { code: 'CAD', name: 'Dólar canadiense' },
  { code: 'CHF', name: 'Franco suizo' },
  { code: 'CNY', name: 'Yuan chino' },
  { code: 'SEK', name: 'Corona sueca' },
  { code: 'NZD', name: 'Dólar neozelandés' },
  { code: 'KRW', name: 'Won surcoreano' },
  { code: 'SGD', name: 'Dólar de Singapur' },
  { code: 'NOK', name: 'Corona noruega' },
  { code: 'MXN', name: 'Peso mexicano' },
  { code: 'INR', name: 'Rupia india' },
  { code: 'BRL', name: 'Real brasileño' },
  { code: 'RUB', name: 'Rublo ruso' },
  { code: 'ZAR', name: 'Rand sudafricano' },
  { code: 'TRY', name: 'Lira turca' },
  { code: 'HKD', name: 'Dólar de Hong Kong' },
  { code: 'IDR', name: 'Rupia indonesia' },
  { code: 'THB', name: 'Baht tailandés' },
  { code: 'PHP', name: 'Peso filipino' },
  { code: 'MYR', name: 'Ringgit malasio' },
  { code: 'COP', name: 'Peso colombiano' },
  { code: 'ARS', name: 'Peso argentino' },
  { code: 'CLP', name: 'Peso chileno' },
  { code: 'PEN', name: 'Sol peruano' },
  { code: 'BOB', name: 'Boliviano' },
  { code: 'PYG', name: 'Guaraní paraguayo' },
  { code: 'UYU', name: 'Peso uruguayo' },
  { code: 'CRC', name: 'Colón costarricense' },
  { code: 'GTQ', name: 'Quetzal guatemalteco' },
  { code: 'HNL', name: 'Lempira hondureña' },
  { code: 'NIO', name: 'Córdoba nicaragüense' },
  { code: 'DOP', name: 'Peso dominicano' },
  { code: 'PAB', name: 'Balboa panameño' },
  { code: 'VES', name: 'Bolívar venezolano' },
  { code: 'BMD', name: 'Dólar de Bermudas' },
  { code: 'BSD', name: 'Dólar bahameño' },
  { code: 'KYD', name: 'Dólar de las Islas Caimán' },
  { code: 'XCD', name: 'Dólar del Caribe Oriental' },
  { code: 'BBD', name: 'Dólar de Barbados' },
  { code: 'TTD', name: 'Dólar de Trinidad y Tobago' },
  { code: 'BZD', name: 'Dólar de Belice' },
  { code: 'JMD', name: 'Dólar jamaiquino' },
  { code: 'SRD', name: 'Dólar surinamés' },
  { code: 'ANG', name: 'Florín de las Antillas Neerlandesas' },
  { code: 'AWG', name: 'Florín arubeño' },
  { code: 'GYD', name: 'Dólar guyanés' },
  { code: 'HTG', name: 'Gourde haitiano' },
  { code: 'SVC', name: 'Colón salvadoreño' },
];

export interface Currency { code?: string; name: string };